// midi-sink desktop app (PROJECT_SPEC.md §1; Phase 5 §2 — the harness
// graduated to a product): GLFW window whose surface the core drives
// (CAMetalLayer / HWND / host-owned GL), frame loop driving
// sumi_update/sumi_render, MIDI from midi_harness.cpp, and the shared
// settings window (settings_ui.cpp — Dear ImGui in a second GLFW window, one
// implementation on macOS, Windows and Linux; DECISIONS_4 #2).
//
// Mouse gestures (always on — this IS the marble instrument):
//   left click        -> sumi_add_drop   (ink; ring parity alternates)
//   left drag         -> sumi_add_tine   (one segment per cursor move)
//   Shift+left drag   -> sumi_add_pinch  (drag distance = k delta, drag angle
//                                         = fold axis)
//   right drag        -> sumi_add_vortex (at the cursor, strength ~ drag
//                                         speed; profile from settings)
//   middle drag       -> sumi_add_wake   (the stylus doublet; scroll wheel
//                                         adjusts the tip radius)
//   Cmd/Ctrl + ,      -> show the settings window
//
// Everything else — the debug keys, the scripted DONE tests, --field-dump —
// is the lab bench in dev_tools.cpp and needs --dev (DECISIONS_4 #5).
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>

#include "sumi_core.h"
#include "app_settings.h"
#include "settings_ui.h"
#include "dev_tools.h"
#include "midi_harness.h"
#include "app_icon.h"   // generated by tools/gen_icons.py (X11 / Win32 window icon)

#if defined(_WIN32)
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3native.h>
#elif defined(__APPLE__)
#include "metal_layer_glue.h"
#endif
// Linux: SUMI_HARNESS_GL is defined by CMake — the host owns the GL context
// (§5.1) and the only GL-side calls the app makes are GLFW's.

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

#ifndef SUMI_APP_VERSION
#define SUMI_APP_VERSION "0.0.0-dev"
#endif
#ifndef SUMI_GIT_COMMIT
#define SUMI_GIT_COMMIT "unknown"
#endif

// Gesture tuning (host-side defaults; normalized canvas-height units).
static const float  DROP_RADIUS       = 0.06f;
static const float  TINE_ALPHA        = 0.035f;
static const float  TINE_MAG_SCALE    = 1.0f;    // magnitude = segment length
static const float  VORTEX_RADIUS     = 0.18f;
static const float  VORTEX_STRENGTH   = 4.0f;    // radians per unit drag speed
static const float  PINCH_DRAG_K      = 4.0f;    // k delta per unit of drag distance
static const double DRAG_THRESHOLD_PX = 5.0;

struct AppState {
    sumi_instance_t* inst = nullptr;
    void*        midi = nullptr;
    AppSettings* settings = nullptr;
    SettingsUi*  ui = nullptr;
    bool         dev = false;
    bool         settings_changed = false;   // apply + persist after the frame
    // left button
    bool   left_down = false, left_dragged = false, left_pinch = false;
    double lx = 0.0, ly = 0.0;
    // right button
    bool   right_down = false;
    double rx = 0.0, ry = 0.0;
    // middle button (v0.4 wake)
    bool   mid_down = false;
    double mx = 0.0, my = 0.0;
    float  wake_tip = 0.02f;        // a, canvas-height units (scroll adjusts)
};

static void log_cb(int level, const char* msg, void* /*user*/) {
    static const char* names[] = {"PANIC", "ERROR", "WARN", "INFO"};
    const char* name = (level >= 0 && level <= 3) ? names[level] : "?";
    std::fprintf(stderr, "[sumi %s] %s\n", name, msg);
}

static void glfw_error_cb(int code, const char* desc) {
    std::fprintf(stderr, "[glfw %d] %s\n", code, desc);
}

static void framebuffer_size_cb(GLFWwindow* window, int w, int h) {
    AppState* app = (AppState*)glfwGetWindowUserPointer(window);
    if (!app || !app->inst || w <= 0 || h <= 0) return;
    float xscale = 1.0f, yscale = 1.0f;
    glfwGetWindowContentScale(window, &xscale, &yscale);
    (void)yscale;
    sumi_resize(app->inst, (uint32_t)w, (uint32_t)h, xscale);
}

// Cursor position -> normalized [0,1] canvas coords (v grows downward, which
// matches the field's texture space).
static void norm_pos(GLFWwindow* window, double px, double py, float* nx, float* ny) {
    int w = 1, h = 1;
    glfwGetWindowSize(window, &w, &h);
    *nx = (float)(px / (double)(w > 0 ? w : 1));
    *ny = (float)(py / (double)(h > 0 ? h : 1));
}

// Segment length in aspect-corrected space (canvas-height units).
static float segment_len_ac(GLFWwindow* window, double x0, double y0, double x1, double y1) {
    int w = 1, h = 1;
    glfwGetWindowSize(window, &w, &h);
    const float dx = (float)((x1 - x0) / (double)(h > 0 ? h : 1));   // /h: ac units
    const float dy = (float)((y1 - y0) / (double)(h > 0 ? h : 1));
    return std::sqrt(dx * dx + dy * dy);
}

static void key_cb(GLFWwindow* window, int key, int /*scancode*/, int action, int mods) {
    if (action != GLFW_PRESS) return;
    AppState* app = (AppState*)glfwGetWindowUserPointer(window);
    if (!app || !app->inst) return;
    // The platform's "Preferences" chord is the one binding a release build
    // keeps: it brings the settings window back after the user closed it.
#if defined(__APPLE__)
    const bool prefs_mod = (mods & GLFW_MOD_SUPER) != 0;
#else
    const bool prefs_mod = (mods & GLFW_MOD_CONTROL) != 0;
#endif
    if (key == GLFW_KEY_COMMA && prefs_mod) {
        if (app->ui) app->ui->show();
        app->settings->settings_open = true;
        app->settings_changed = true;
        return;
    }
    if (!app->dev) return;   // zero debug keys without --dev
    bool changed = false;
    dev_key(window, *app->settings, app->inst, app->midi, key, mods, &changed);
    if (changed) app->settings_changed = true;
}

static void mouse_button_cb(GLFWwindow* window, int button, int action, int /*mods*/) {
    AppState* app = (AppState*)glfwGetWindowUserPointer(window);
    if (!app || !app->inst) return;
    double cx = 0.0, cy = 0.0;
    glfwGetCursorPos(window, &cx, &cy);

    if (button == GLFW_MOUSE_BUTTON_LEFT) {
        if (action == GLFW_PRESS) {
            app->left_down = true;
            app->left_dragged = false;
            app->left_pinch = (glfwGetKey(window, GLFW_KEY_LEFT_SHIFT) == GLFW_PRESS ||
                               glfwGetKey(window, GLFW_KEY_RIGHT_SHIFT) == GLFW_PRESS);
            app->lx = cx; app->ly = cy;
        } else if (action == GLFW_RELEASE && app->left_down) {
            app->left_down = false;
            if (!app->left_dragged && !app->left_pinch) {
                float nx, ny;
                norm_pos(window, cx, cy, &nx, &ny);
                sumi_add_drop(app->inst, nx, ny, DROP_RADIUS, 0);
            }
        }
    } else if (button == GLFW_MOUSE_BUTTON_RIGHT) {
        if (action == GLFW_PRESS) {
            app->right_down = true;
            app->rx = cx; app->ry = cy;
        } else if (action == GLFW_RELEASE) {
            app->right_down = false;
        }
    } else if (button == GLFW_MOUSE_BUTTON_MIDDLE) {
        if (action == GLFW_PRESS) {
            app->mid_down = true;
            app->mx = cx; app->my = cy;
        } else if (action == GLFW_RELEASE) {
            app->mid_down = false;
        }
    }
}

// Scroll wheel: wake tip radius (v0.4 — the stylus maps it from pressure;
// the mouse has no pressure, so the wheel stands in).
static void scroll_cb(GLFWwindow* window, double /*sx*/, double sy) {
    AppState* app = (AppState*)glfwGetWindowUserPointer(window);
    if (!app) return;
    app->wake_tip *= (sy > 0.0) ? 1.15f : (sy < 0.0 ? 1.0f / 1.15f : 1.0f);
    if (app->wake_tip < 0.005f) app->wake_tip = 0.005f;
    if (app->wake_tip > 0.080f) app->wake_tip = 0.080f;
}

static void cursor_pos_cb(GLFWwindow* window, double cx, double cy) {
    AppState* app = (AppState*)glfwGetWindowUserPointer(window);
    if (!app || !app->inst) return;

    if (app->left_down) {
        const double dx = cx - app->lx, dy = cy - app->ly;
        if (dx * dx + dy * dy >= DRAG_THRESHOLD_PX * DRAG_THRESHOLD_PX) {
            float x0, y0, x1, y1;
            norm_pos(window, app->lx, app->ly, &x0, &y0);
            norm_pos(window, cx, cy, &x1, &y1);
            const float mag = segment_len_ac(window, app->lx, app->ly, cx, cy);
            if (app->left_pinch) {
                // §4.3(5): drag distance = k delta, drag angle = fold axis.
                int w = 1, h = 1;
                glfwGetWindowSize(window, &w, &h);
                const float aspect = (float)w / (float)(h > 0 ? h : 1);
                const float angle = std::atan2(y1 - y0, (x1 - x0) * aspect);
                sumi_add_pinch(app->inst, x1, y1, mag * PINCH_DRAG_K, angle);
            } else {
                sumi_add_tine(app->inst, x0, y0, x1, y1, TINE_ALPHA, mag * TINE_MAG_SCALE);
            }
            app->left_dragged = true;
            app->lx = cx; app->ly = cy;
        }
    }
    if (app->mid_down) {
        const double dx = cx - app->mx, dy = cy - app->my;
        if (dx * dx + dy * dy >= DRAG_THRESHOLD_PX * DRAG_THRESHOLD_PX) {
            float x0, y0, x1, y1;
            norm_pos(window, app->mx, app->my, &x0, &y0);
            norm_pos(window, cx, cy, &x1, &y1);
            sumi_add_wake(app->inst, x0, y0, x1, y1, app->wake_tip);
            app->mx = cx; app->my = cy;
        }
    }
    if (app->right_down) {
        const double dx = cx - app->rx, dy = cy - app->ry;
        if (dx * dx + dy * dy >= DRAG_THRESHOLD_PX * DRAG_THRESHOLD_PX) {
            float nx, ny;
            norm_pos(window, cx, cy, &nx, &ny);
            const float speed = segment_len_ac(window, app->rx, app->ry, cx, cy);
            sumi_add_vortex(app->inst, nx, ny, speed * VORTEX_STRENGTH, VORTEX_RADIUS,
                            app->settings->params.vortex_profile);
            app->rx = cx; app->ry = cy;
        }
    }
}

static void print_usage(const char* argv0) {
    std::fprintf(stderr,
        "midi-sink %s (%s)\n"
        "usage: %s [--dev] [--help] [--version]\n"
        "  --dev      enable the lab bench: debug keys, scripted tests, --field-dump\n"
        "  Settings live in the settings window (Cmd/Ctrl + , brings it back).\n",
        SUMI_APP_VERSION, SUMI_GIT_COMMIT, argv0);
}

int main(int argc, char** argv) {
    bool dev = false;
    DevOptions devopts;
    // --dev must be seen before any lab-bench flag is accepted; scan for it
    // first so the order on the command line does not matter.
    for (int i = 1; i < argc; i++) {
        if (std::strcmp(argv[i], "--dev") == 0) dev = true;
    }
    for (int i = 1; i < argc; i++) {
        if (std::strcmp(argv[i], "--dev") == 0) continue;
        if (std::strcmp(argv[i], "--help") == 0 || std::strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            if (dev) dev_print_usage(argv[0]);
            return 0;
        }
        if (std::strcmp(argv[i], "--version") == 0) {
            const uint32_t v = sumi_version();
            std::printf("midi-sink %s (commit %s, libsumi %u.%u.%u)\n", SUMI_APP_VERSION,
                        SUMI_GIT_COMMIT, v >> 16, (v >> 8) & 0xFF, v & 0xFF);
            return 0;
        }
        if (!dev) {
            std::fprintf(stderr, "midi-sink: '%s' is a lab-bench option; run with --dev to enable it.\n",
                         argv[i]);
            print_usage(argv[0]);
            return 2;
        }
        const int r = dev_parse_arg(devopts, argc, argv, i);
        if (r == 0) {
            std::fprintf(stderr, "midi-sink: unknown option '%s'\n", argv[i]);
            dev_print_usage(argv[0]);
            return 2;
        }
        if (r < 0) return 2;
    }

    glfwSetErrorCallback(glfw_error_cb);
#if defined(__APPLE__)
    // GLFW's Cocoa default chdir()s a bundled app into Contents/Resources,
    // which would silently redirect every relative path a user or a script
    // gives us (prints, --field-dump). Keep the launching cwd.
    glfwInitHint(GLFW_COCOA_CHDIR_RESOURCES, GLFW_FALSE);
#endif
    if (!glfwInit()) {
        std::fprintf(stderr, "glfwInit failed\n");
        return 1;
    }

    // Desktop-entry identity. A Wayland compositor takes an app's icon and
    // name from the .desktop file it matches to the toplevel's app_id (never
    // from the client), so this string must equal the basename of
    // packaging/linux/midi-sink.desktop; the X11 hints feed WM_CLASS, which
    // that file's StartupWMClass matches. Ignored on other platforms.
    glfwWindowHintString(GLFW_WAYLAND_APP_ID, "midi-sink");
    glfwWindowHintString(GLFW_X11_CLASS_NAME, "midi-sink");
    glfwWindowHintString(GLFW_X11_INSTANCE_NAME, "midi-sink");

#if defined(SUMI_HARNESS_GL)
    // §5.1 GL exception: the host creates the context. GL 4.1 core — the
    // spec's Linux baseline (macOS's GL ceiling); forward-compat off (GLFW's
    // default) per the step-12 brief.
    glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_API);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
#else
    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
#endif
    GLFWwindow* window = glfwCreateWindow(1280, 720, "midi-sink", nullptr, nullptr);
    if (!window) {
        glfwTerminate();
        return 1;
    }

    // Window/taskbar icon. Only X11 and Win32 implement glfwSetWindowIcon —
    // Wayland takes the icon from a .desktop file and macOS from the .app
    // bundle's CFBundleIconFile (DECISIONS_4 #6).
    const int glfw_platform = glfwGetPlatform();
    if (glfw_platform == GLFW_PLATFORM_X11 || glfw_platform == GLFW_PLATFORM_WIN32) {
        const GLFWimage icons[3] = {
            {sumi_icon_64_size, sumi_icon_64_size, (unsigned char*)sumi_icon_64},
            {sumi_icon_48_size, sumi_icon_48_size, (unsigned char*)sumi_icon_48},
            {sumi_icon_32_size, sumi_icon_32_size, (unsigned char*)sumi_icon_32},
        };
        glfwSetWindowIcon(window, 3, icons);
    }

    // Per-platform surface prep (§5.1): macOS attaches a CAMetalLayer the
    // core drives; Windows hands the raw HWND and the core creates the D3D11
    // device + DXGI swapchain itself; Linux/GL makes the host-owned context
    // current (BEFORE sumi_create) and passes a NULL handle — the core
    // renders into the bound default framebuffer and the host swaps.
#if defined(_WIN32)
    void* surface = (void*)glfwGetWin32Window(window);
    const sumi_backend_t backend = SUMI_BACKEND_D3D11;
    if (!surface) {
        std::fprintf(stderr, "glfwGetWin32Window failed\n");
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }
#elif defined(__APPLE__)
    void* surface = sumi_macos_attach_metal_layer(window);
    const sumi_backend_t backend = SUMI_BACKEND_METAL;
    if (!surface) {
        std::fprintf(stderr, "failed to attach CAMetalLayer\n");
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }
#else
    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);   // vsync pacing, matching Metal/D3D11 (DECISIONS_2 #17)
    void* surface = nullptr;
    const sumi_backend_t backend = SUMI_BACKEND_GL;
#endif

    int fbw = 0, fbh = 0;
    glfwGetFramebufferSize(window, &fbw, &fbh);
    float xscale = 1.0f, yscale = 1.0f;
    glfwGetWindowContentScale(window, &xscale, &yscale);
    (void)yscale;

    sumi_config_t config = {};
    config.native_surface_handle = surface;
    config.backend = backend;
    config.width = (uint32_t)fbw;
    config.height = (uint32_t)fbh;
    config.pixel_ratio = xscale;
    config.log_cb = log_cb;

    sumi_instance_t* inst = sumi_create(&config);
    if (!inst) {
        std::fprintf(stderr, "sumi_create failed\n");
#if defined(__APPLE__)
        sumi_macos_detach_metal_layer(window, surface);
#endif
        glfwDestroyWindow(window);
        glfwTerminate();
        return 1;
    }
    auto teardown = [&](void* midi, SettingsUi* ui) {
        if (ui) ui->shutdown();
        if (midi) sumi_midi_harness_stop(midi);
        sumi_destroy(inst);
#if defined(__APPLE__)
        sumi_macos_detach_metal_layer(window, surface);
#endif
        glfwDestroyWindow(window);
        glfwTerminate();
    };

    const uint32_t ver = sumi_version();
    std::printf("midi-sink %s (commit %s, libsumi %u.%u.%u)%s\n", SUMI_APP_VERSION, SUMI_GIT_COMMIT,
                ver >> 16, (ver >> 8) & 0xFF, ver & 0xFF, dev ? "  [--dev lab bench]" : "");

    // Scripted run-and-exit modes (--field-dump, the test battery) run on the
    // PRISTINE core state — never on a user's persisted settings — so the
    // §4.6 fixture and the DONE numbers stay deterministic.
    if (dev) {
        const int code = dev_run_scripted(devopts, window, inst);
        if (code >= 0) {
            teardown(nullptr, nullptr);
            return code;
        }
    }

    // ---- the instrument ----
    void* midi = sumi_midi_harness_start(inst);
    if (!midi) {
        std::fprintf(stderr, "[midi] harness failed to start (continuing without MIDI)\n");
    }

    AppSettings settings;
    sumi_params_t core_defaults;
    sumi_get_params(inst, &core_defaults);
    app_settings_defaults(settings, core_defaults);
    const std::string settings_path = app_settings_path();
    if (app_settings_load(settings, settings_path)) {
        std::printf("[settings] loaded %s\n", settings_path.c_str());
    } else {
        // First run: write the defaults now, so the file exists even if the
        // session ends without a clean exit.
        app_settings_save(settings, settings_path);
        std::printf("[settings] first run - defaults written to %s\n", settings_path.c_str());
    }
    DevLoop devloop;
    if (dev) dev_loop_begin(devloop, devopts, settings, inst, midi);
    app_settings_apply(settings, inst, midi);

    SettingsUi ui;
    SettingsUiInfo info{SUMI_APP_VERSION, SUMI_GIT_COMMIT, dev};
    const bool ui_ok = ui.init(window, info);
    if (!ui_ok) {
        std::fprintf(stderr, "[settings] settings window unavailable on this system\n");
    } else if (settings.settings_open || !settings.first_run_dismissed) {
        ui.show();
    }

    AppState app;
    app.inst = inst;
    app.midi = midi;
    app.settings = &settings;
    app.ui = ui_ok ? &ui : nullptr;
    app.dev = dev;
    glfwSetWindowUserPointer(window, &app);
    glfwSetFramebufferSizeCallback(window, framebuffer_size_cb);
    glfwSetMouseButtonCallback(window, mouse_button_cb);
    glfwSetCursorPosCallback(window, cursor_pos_cb);
    glfwSetScrollCallback(window, scroll_cb);
    glfwSetKeyCallback(window, key_cb);
    // Do NOT refocus the canvas here: on a display too narrow for both
    // windows side by side the settings window overlaps the canvas, and a
    // later focus would bury it behind the canvas on first launch.

    double last = glfwGetTime();
    uint64_t frames = 0;
    while (!glfwWindowShouldClose(window)) {
        const double now = glfwGetTime();
        const double dt = now - last;
        last = now;

        if (dev) dev_loop_pre_update(devloop, inst);

        sumi_update(inst, dt);
        sumi_render(inst);
#if defined(SUMI_HARNESS_GL)
        glfwSwapBuffers(window);   // §5.1: the host presents on GL
#endif
        frames++;

        glfwPollEvents();
        sumi_midi_harness_poll(midi);

        if (ui_ok) {
            if (ui.frame(settings, inst, midi, window)) app.settings_changed = true;
            if (ui.consume_closed()) {
                settings.settings_open = false;
                app.settings_changed = true;
            }
        }
        if (dev) {
            dev_loop_post_frame(devloop, window, inst, settings, &app.settings_changed,
                                now, dt, frames);
        }
        if (app.settings_changed) {
            app.settings_changed = false;
            settings.settings_open = ui_ok && ui.visible();
            app_settings_apply(settings, inst, midi);
            app_settings_save(settings, settings_path);
        }
    }

    settings.settings_open = ui_ok && ui.visible();
    app_settings_save(settings, settings_path);
    if (dev) dev_loop_report(devloop, inst, glfwGetTime(), frames);
    teardown(midi, ui_ok ? &ui : nullptr);
    return 0;
}
