#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy", "matplotlib", "scipy"]
# ///
"""suzu_compare.py — compare a fitted Suzu voice profile against its reference sample profile.

Part of fitting Suzu patches to VCSL instruments (Phase 10, HANDOFF_SUZU_VCSL.md).
Takes the profile directories generated by midi-sink --dev --voxo-profile:
  - sample profile (from --voxo-preset <dspreset>)
  - fitted Suzu profile (from --voxo-source suzu --preset <fitted.json>)
Calculates quantitative metrics:
  - spectral distance in dB per note over harmonics
  - peak and RMS level tracking error
  - T60 decay tracking error
Generates a 3-panel comparison figure with the two curves overlaid.

Usage:
  uv run tools/suzu_compare.py --sample-dir <dir> --suzu-dir <dir>
                               [--title <title>] [--out <figure.png>]
"""
import argparse
import csv
import math
import os
import sys

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.io import wavfile


def read_profile_csv(path):
    rows = list(csv.DictReader(open(path, "r", encoding="utf-8")))
    notes = np.array([int(r["note"]) for r in rows])
    peaks = np.array([float(r["peak_dbfs"]) for r in rows])
    rmss = np.array([float(r["rms_dbfs"]) for r in rows])
    h1 = np.array([float(r["h1_db"]) for r in rows])
    h2 = np.array([float(r["h2_db"]) for r in rows])
    h3 = np.array([float(r["h3_db"]) for r in rows])
    return {
        "notes": notes,
        "peak": peaks,
        "rms": rmss,
        "h1": h1,
        "h2": h2,
        "h3": h3
    }


def estimate_t60_per_note(wav_path, note_count=88, sample_rate=48000):
    rate, data = wavfile.read(wav_path)
    if data.ndim == 2:
        data = data[:, 0]
    if data.dtype.kind == "i":
        data = data.astype(np.float64) / float(2 ** (8 * data.dtype.itemsize - 1))
    per_note = int(0.8 * rate)  # 0.5s held + 0.3s released
    t60_list = []
    for i in range(note_count):
        seg = data[i * per_note : (i + 1) * per_note]
        if len(seg) == 0:
            t60_list.append(0.0)
            continue
        # Frame energy
        frame_sz = 256
        frames = [np.mean(seg[j:j+frame_sz] ** 2) for j in range(0, len(seg) - frame_sz, frame_sz // 2)]
        frames = np.sqrt(np.maximum(frames, 1e-12))
        max_e = np.max(frames) if len(frames) > 0 else 1e-6
        db = 20.0 * np.log10(np.maximum(frames / max_e, 1e-6))
        # Fit decay
        p_idx = np.argmax(frames)
        t_ax = np.arange(len(frames)) * (frame_sz / 2.0 / rate)
        pts = np.where((t_ax >= t_ax[p_idx]) & (db >= -25.0))[0]
        if len(pts) >= 4:
            slope, _ = np.polyfit(t_ax[pts] - t_ax[pts[0]], db[pts], 1)
            t60 = float(-60.0 / slope) if slope < -0.1 else 20.0
        else:
            t60 = 2.0
        t60_list.append(max(0.01, min(30.0, t60)))
    return np.array(t60_list)


def main():
    ap = argparse.ArgumentParser(description="Compare fitted Suzu profile against sample reference profile")
    ap.add_argument("--sample-dir", required=True, help="Directory containing sample profile.csv and profile.wav")
    ap.add_argument("--suzu-dir", required=True, help="Directory containing suzu profile.csv and profile.wav")
    ap.add_argument("--title", default=None, help="Comparison title")
    ap.add_argument("--out", default=None, help="Output PNG path")
    args = ap.parse_args()

    sample_csv = os.path.join(args.sample_dir, "profile.csv")
    suzu_csv = os.path.join(args.suzu_dir, "profile.csv")
    if not os.path.exists(sample_csv) or not os.path.exists(suzu_csv):
        print(f"Error: Missing profile.csv in {args.sample_dir} or {args.suzu_dir}", file=sys.stderr)
        return 1

    s_data = read_profile_csv(sample_csv)
    z_data = read_profile_csv(suzu_csv)

    # Align notes
    common_notes = np.intersect1d(s_data["notes"], z_data["notes"])
    if len(common_notes) == 0:
        print("Error: No overlapping MIDI notes between profiles", file=sys.stderr)
        return 1

    idx_s = [np.where(s_data["notes"] == n)[0][0] for n in common_notes]
    idx_z = [np.where(z_data["notes"] == n)[0][0] for n in common_notes]

    notes = common_notes
    peak_s = s_data["peak"][idx_s]
    peak_z = z_data["peak"][idx_z]
    rms_s = s_data["rms"][idx_s]
    rms_z = z_data["rms"][idx_z]

    h1_s, h1_z = s_data["h1"][idx_s], z_data["h1"][idx_z]
    h2_s, h2_z = s_data["h2"][idx_s], z_data["h2"][idx_z]
    h3_s, h3_z = s_data["h3"][idx_s], z_data["h3"][idx_z]

    # Calculate metrics
    # Harmonic spectral distance in dB (RMS over h1..h3)
    # Ignore values at or below -150 dB floor
    mask_h = (h1_s > -120) & (h1_z > -120)
    spec_dist_per_note = np.sqrt(((h1_z - h1_s) ** 2 + (h2_z - h2_s) ** 2 + (h3_z - h3_s) ** 2) / 3.0)
    mean_spec_dist = float(np.mean(spec_dist_per_note[mask_h])) if np.any(mask_h) else 0.0

    peak_err = np.abs(peak_z - peak_s)
    mean_peak_err = float(np.mean(peak_err))

    # T60 estimation if wavs exist
    sample_wav = os.path.join(args.sample_dir, "profile.wav")
    suzu_wav = os.path.join(args.suzu_dir, "profile.wav")
    t60_err = 0.0
    has_wavs = os.path.exists(sample_wav) and os.path.exists(suzu_wav)
    if has_wavs:
        t60_s = estimate_t60_per_note(sample_wav, len(s_data["notes"]))[idx_s]
        t60_z = estimate_t60_per_note(suzu_wav, len(z_data["notes"]))[idx_z]
        t60_err = float(np.mean(np.abs(t60_z - t60_s)))

    title = args.title or f"Comparison — Suzu vs {os.path.basename(os.path.abspath(args.sample_dir))}"
    out_path = args.out or os.path.join(args.suzu_dir, "comparison.png")

    fig, axes = plt.subplots(3, 1, figsize=(12, 11), constrained_layout=True)
    fig.suptitle(f"{title}\nSpectral distance: {mean_spec_dist:.2f} dB, Peak error: {mean_peak_err:.2f} dB" + (f", T60 error: {t60_err:.2f} s" if has_wavs else ""), fontsize=12)

    # Panel 1: Levels across keyboard
    ax = axes[0]
    ax.plot(notes, peak_s, "--", color="#1f77b4", label="Sample peak", lw=1.5, alpha=0.8)
    ax.plot(notes, peak_z, "-", color="#1f77b4", label="Suzu fitted peak", lw=1.8)
    ax.plot(notes, rms_s, "--", color="#ff7f0e", label="Sample RMS", lw=1.5, alpha=0.8)
    ax.plot(notes, rms_z, "-", color="#ff7f0e", label="Suzu fitted RMS", lw=1.8)
    ax.set_xlabel("MIDI note (velocity 100, held 0.5 s, released 0.3 s)")
    ax.set_ylabel("level, dBFS")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="lower left", ncol=2)
    ax.set_title(f"Level across keyboard — Peak tracking error: {mean_peak_err:.2f} dB", fontsize=10)
    for oct in range(24, 109, 12):
        ax.axvline(oct, color="k", alpha=0.08)

    # Panel 2: Harmonics across keyboard
    ax = axes[1]
    ax.plot(notes, h1_s, "--", color="#2ca02c", label="Sample h1", lw=1.4, alpha=0.7)
    ax.plot(notes, h1_z, "-", color="#2ca02c", label="Suzu h1", lw=1.6)
    ax.plot(notes, h2_s, "--", color="#d62728", label="Sample h2", lw=1.4, alpha=0.7)
    ax.plot(notes, h2_z, "-", color="#d62728", label="Suzu h2", lw=1.6)
    ax.plot(notes, h3_s, "--", color="#9467bd", label="Sample h3", lw=1.4, alpha=0.7)
    ax.plot(notes, h3_z, "-", color="#9467bd", label="Suzu h3", lw=1.6)
    ax.set_ylim(-90, 0)
    ax.set_xlabel("MIDI note")
    ax.set_ylabel("level, dBFS")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="lower left", ncol=3)
    ax.set_title(f"First three harmonics — Mean spectral distance: {mean_spec_dist:.2f} dB", fontsize=10)

    # Panel 3: Spectral distance error profile
    ax = axes[2]
    ax.plot(notes, spec_dist_per_note, color="#d62728", lw=1.6, label="Spectral distance (dB)")
    ax.axhline(mean_spec_dist, color="#d62728", linestyle=":", label=f"Mean: {mean_spec_dist:.2f} dB")
    ax.set_xlabel("MIDI note")
    ax.set_ylabel("Error, dB")
    ax.set_ylim(0, max(25.0, np.max(spec_dist_per_note) + 5.0))
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right")
    ax.set_title("Harmonic distance per note between Suzu patch and reference sample", fontsize=10)

    fig.savefig(out_path, dpi=110)
    plt.close(fig)

    print(f"Comparison figure written: {out_path}")
    print(f"--- Verification Results ---")
    print(f"Notes evaluated: {len(notes)} ({notes.min()}..{notes.max()})")
    print(f"Mean harmonic spectral distance: {mean_spec_dist:.2f} dB")
    print(f"Mean peak level error:           {mean_peak_err:.2f} dB")
    if has_wavs:
        print(f"Mean T60 decay error:            {t60_err:.2f} s")
    return 0


if __name__ == "__main__":
    sys.exit(main())

